### ISSUE TITLE
db, mac OS

### ISSUE THREAD

**Issue by t-cool** [t-sin/niko#4] opened 2018-05-05 04:20 UTC
I'm setting up niko right now, but I face with the following error:

```
$ qlot exec lake server
Making core for Roswell...
building dump:/Users/noguchihiroki/.roswell/impls/x86-64/darwin/sbcl-bin/1.4.4/dump/lake.core
up to date. stop

> niko@0.1.0 dev-server /Users/noguchihiroki/.roswell/local-projects/t-sin/niko
> webpack-dev-server --config ./config/webpack.config.js

Project is running at http://localhost:8080/
webpack output is served from http://localhost:8080/
404s will fallback to /index.html
Hunchentoot server is going to start.
Listening on localhost:5000.
Hash: 50fe0508e48791047798
Version: webpack 3.11.0
Time: 1218ms
           Asset     Size  Chunks                    Chunk Names
assets/bundle.js   355 kB       0  [emitted]  [big]  main
assets/style.css  0 bytes       0  [emitted]         main
   [0] (webpack)/hot/log.js 1.04 kB {0} [built]
   [1] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [2] (webpack)-dev-server/client?http://localhost:8080 7.93 kB {0} [built]
   [5] (webpack)/hot/log-apply-result.js 1.31 kB {0} [built]
   [6] multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./assets/javascripts/main.js 76 bytes {0} [built]
   [7] ./node_modules/url/url.js 23.3 kB {0} [built]
  [14] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [16] ./node_modules/loglevel/lib/loglevel.js 7.86 kB {0} [built]
  [17] (webpack)-dev-server/client/socket.js 1.08 kB {0} [built]
  [19] (webpack)-dev-server/client/overlay.js 3.67 kB {0} [built]
  [24] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [26] (webpack)/hot/dev-server.js 1.61 kB {0} [built]
  [27] (webpack)/hot/only-dev-server.js 2.37 kB {0} [built]
  [28] ./assets/javascripts/main.js 205 bytes {0} [built]
  [29] ./assets/stylesheets/main.scss 41 bytes {0} [built]
    + 19 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!assets/stylesheets/main.scss:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./assets/stylesheets/main.scss 162 bytes {0} [built]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]

webpack: Compiled successfully.
127.0.0.1 - [05/May/2018:13:18:47 +09:00] "GET /robots.txt HTTP/1.1" 404 683 "-" "-"
127.0.0.1 - [05/May/2018:13:18:47 +09:00] "GET / HTTP/1.1" 200 537 "-" "-"
127.0.0.1 - [05/May/2018:13:18:47 +09:00] "GET /favicon.ico HTTP/1.1" 404 683 "-" "-"
127.0.0.1 - [05/May/2018:13:18:49 +09:00] "GET /users/add HTTP/1.1" 200 831 "-" "-"
127.0.0.1 - [05/May/2018:13:19:17 +09:00] "GET /robots.txt HTTP/1.1" 404 683 "-" "-"
#<DEXADOR.ERROR:HTTP-REQUEST-UNAUTHORIZED {1004102F73}>
127.0.0.1 - [05/May/2018:13:19:18 +09:00] "POST /users/add HTTP/1.1" 500 51267 "-" "-"
```

**Comment by t-sin** [comment] 2018-05-05 06:10
@t-cool This is caused by clackup without github API tokens. *Niko* needs two API tokens:

- github API token
- slack API token

These tokens should be specified when start server, like this:

```sh
$ GITHUB_TOKEN=hogehoge SLACK_TOKEN=fugafuga qlot exec lake server
```

I'm sorry for undocumented, because *niko* is still under depelopment.

**Comment by t-sin** [comment] 2018-12-11 06:37
@t-cool Can I close this issue?

**Closed** 2018-12-11 12:52 UTC
